### ISSUE TITLE
Native Mac/Windows support

### ISSUE THREAD

**Issue by peters95** [containers/podman.io_old#315]
It would be ideal to have native mac and windows support to further the adoption of podman in the community. Users do not want to have a Linux VM just to use podman on these platforms. Furthermore, users won't read the entire README to find out that you really only support Linux and not Mac/Windows without a Linux VM.

**Comment by TomSweeneyRedHat** [comment]
@peters95 I agree and would love to see someone move this forward.  However, the better project to request this against would be podman, this one is targeted towards blog posts and documentation of that project.  I've just created: https://github.com/containers/podman/issues/8452 to carry that conversation forward and will close this one now.

**Comment by rhatdan** [comment]
@peters95 Podman and Docker for the most part launch Linux Containers.  In order to run a Linux Container, you need a Linux Kernel, which requires a VM (Or a hidden VM like WSL2) .  There is a concept of Windows containers, but when most people talk about containers they are talking about Linux.

You can install Podman with brew install for MAC and we have packaging to install Podman on windows as well.
