### ISSUE TITLE
Mastodon @podman_io account

### ISSUE THREAD

**Issue by dperson** [containers/podman.io_old#592]
Now that Twitter has blocked FOSS  clients I've not been back. I'd love to still be able to follow your updates. Thanks!

**Comment by Luap99** [comment]
Sorry for the long silence, I just become aware that we already have an official account there as well:
https://fosstodon.org/@Podman_io

**Comment by TomSweeneyRedHat** [comment]
Apologies for the delay @dperson.  Your issue here started me off trying to figure out how to get a Mastodon account set up, and I figured it out a few weeks later.  But brilliant me forgot to come back here and close this comment and leave a pointer.   So thanks again for the issue/suggestion and I hope you find the new account useful.

Thanks @Luap99 for catching that and closing this.

**Comment by dperson** [comment]
Yes, I found it out there and have been following it. Thanks for your help @Luap99 @TomSweeneyRedHat
